kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: productpage
  namespace: {{ .Values.namespace }}
  labels:
    app: productpage
    app.kubernetes.io/instance: lab.01-deploy-bookinfo
    service: productpage
spec:
  host: productpage-bookinfo.{{ required "A valid .Values.routedeomain entry required!" .Values.routedeomain | lower }}
  to:
    kind: Service
    name: productpage
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
