apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-htpasswd-idp
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift/AWS-ServiceMesh-Lab/install_idp/
    repoURL: https://github.com/tjungbauer/OCP-Lab-Setup
    targetRevision: master
