apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab.09-c1-fault-injection
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Lab.09-C1-Fault-Injection/
    repoURL: https://github.com/tjungbauer/Servicemesh-Lab
    targetRevision: main
