apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab.10-force-mtls
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Lab.10-Force-mTLS/
    repoURL: https://github.com/tjungbauer/Servicemesh-Lab
    targetRevision: master
