apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab.06-a-create-service-entry
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift/AWS-ServiceMesh-Lab/Lab.06-A-Create-ServiceEntry/
    repoURL: https://github.com/tjungbauer/OCP-Lab-Setup
    targetRevision: master
