apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab.03-create-ingress-gateway
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Lab.03-Create-Ingress-Gateway/
    repoURL: https://github.com/tjungbauer/Servicemesh-Lab
    targetRevision: main
