apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab.04-create-simple-virtualservice
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Lab.04-Create-Simple-VirtualServices/
    repoURL: https://github.com/tjungbauer/Servicemesh-Lab
    targetRevision: main
