apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab.09-c2-slow-connection
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift/AWS-ServiceMesh-Lab/Lab.09-C2-Slow-Connection/
    repoURL: https://github.com/tjungbauer/OCP-Lab-Setup
    targetRevision: master
