apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab.05-create-ingress-gateway
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift/AWS-ServiceMesh-Lab/Lab.05-Create-Ingress-Gateway/
    repoURL: https://github.com/tjungbauer/OCP-Lab-Setup
    targetRevision: master
