apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab.00-deploy-servicemesh-operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Lab.00_Deploy_Service_Mesh_Operators/
    repoURL: https://github.com/tjungbauer/Servicemesh-Lab
    targetRevision: main
