apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab.09-mirror-traffic
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Lab.09-B-Mirroring-Traffic/
    repoURL: https://github.com/tjungbauer/Servicemesh-Lab
    targetRevision: master
