apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab.98-deploy-erdemo
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Lab.98-Deploy_ERDemo/
    repoURL: https://github.com/tjungbauer/Servicemesh-Lab
    targetRevision: main
