apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic-bookinfo
  namespace: {{ .Values.cpnamespace }}
spec:
  proxy:
    accessLogging:
      file:
        encoding: TEXT
        name: '/dev/stdout'
    networking:
      trafficControl:
        outbound:
          policy: REGISTRY_ONLY
  version: v2.0
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
