apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic-bookinfo
  namespace: {{ .Values.namespace }}
spec:
  proxy:
    accessLogging:
      file:
        encoding: TEXT
        name: '/dev/stdout'
  version: {{ .Values.cp_version }}
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: {{ .Values.cp_jaeger_storagetype }}
    kiali:
      enabled: {{ .Values.cp_kiali }}
      name: kiali
    grafana:
      enabled: {{ .Values.cp_grafana }}
