apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: {{ .Values.namespace }}
spec:
  members:
    {{- range tuple "small" "medium" "large" }}
    - {{ . }}
    {{- end }}
