apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: {{ .Values.namespace }}
spec:
  members: |-
    {{- range .Values.cp_members }}
    - {{ . }}
    {{- end }}
