apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: worldclock
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - worldclockapi.com
    tls:
      mode: PASSTHROUGH
