apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: worldclock-egress-tls
  namespace: {{ .Values.namespace }}
spec:
  host: worldclockapi.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE # initiates HTTPS for connections to worldclockapi.com
