apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.es.namespace }}
  namespace: {{ .Values.es.namespace }}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: {{ .Values.es.namespace }}
spec:
  channel: '{{ .Values.es.channel }}'
  installPlanApproval: {{ .Values.es.upgradeplan }}
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.es.starting_csv }}
---
