apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
  namespace: {{ .Values.kiali.namespace }}
spec:
  channel: stable
  installPlanApproval: {{ .Values.kiali.upgradeplan }}
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.kiali.starting_csv }}
