apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: {{ .Values.jaeger.namespace }}
spec:
  channel: stable
  installPlanApproval: {{ .Values.jaeger.upgradeplan }}
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.jaeger.starting_csv }}
