kind: Secret
apiVersion: v1
metadata:
  name: htpasswd
  namespace: openshift-config
data:
  htpasswd: >-
    YWRtaW46JGFwcjEkMDEza2JmUzIkSzVqb0hBQXFWdVVkL0Y0UFpTZHN1MQpsb2NhbDokYXByMSQwMTNrYmZTMiRLNWpvSEFBcVZ1VWQvRjRQWlNkc3Ux
type: Opaque
