apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: worldclock
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - worldclockapi.com
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
